import './style.css';
const KEY='mwc_v03', defaults={weight:94,goal:82,kcal:2200,eaten:0,protein:0,carbs:0,fat:0,meals:[],weights:[]};
let s={...defaults,...JSON.parse(localStorage.getItem(KEY)||'{}')};let rec;
const save=()=>localStorage.setItem(KEY,JSON.stringify(s));
function render(){document.querySelector('#app').innerHTML=`<div class="app"><header><div><small>MYWEIGHT COACH</small><h1>Aujourd’hui</h1></div><button id="reset">↻</button></header><main>
<section class="card hero"><div><span>Poids actuel</span><strong>${s.weight} kg</strong><small>Objectif ${s.goal} kg</small></div><div class="ring"><b>${Math.max(0,s.kcal-s.eaten)}</b><small>kcal restantes</small></div></section>
<section class="grid">${[['Calories',s.eaten+' / '+s.kcal],['Protéines',s.protein+' g'],['Glucides',s.carbs+' g'],['Lipides',s.fat+' g']].map(x=>`<div class="card stat"><span>${x[0]}</span><b>${x[1]}</b></div>`).join('')}</section>
<section class="card"><div class="title"><h2>Repas du jour</h2><button id="meal">+ Ajouter</button></div>${s.meals.length?s.meals.map((m,i)=>`<div class="meal"><div><b>${m.name}</b><small>${m.kcal} kcal · P ${m.p}g · G ${m.c}g · L ${m.f}g</small></div><button data-d="${i}">×</button></div>`).join(''):'<p>Aucun repas enregistré.</p>'}</section>
<section class="card"><div class="title"><h2>Poids</h2><button id="weight">+ Pesée</button></div><strong class="big">${s.weight} kg</strong></section></main>
<nav><span>⌂<small>Accueil</small></span><span>◷<small>Journal</small></span><span>⚙<small>Réglages</small></span></nav><button class="mic" id="mic">🎙️</button><div id="toast"></div></div>`;
bind()}
function toast(t){let x=document.querySelector('#toast');x.textContent=t;x.className='show';setTimeout(()=>x.className='',2200)}
function bind(){document.querySelector('#mic').onclick=listen;document.querySelector('#meal').onclick=meal;document.querySelector('#weight').onclick=weight;document.querySelector('#reset').onclick=()=>{localStorage.removeItem(KEY);s={...defaults};render()};document.querySelectorAll('[data-d]').forEach(b=>b.onclick=()=>{let m=s.meals.splice(+b.dataset.d,1)[0];s.eaten-=m.kcal;s.protein-=m.p;s.carbs-=m.c;s.fat-=m.f;save();render()})}
function meal(){let n=prompt('Nom du repas ?','Repas');if(!n)return;let k=+prompt('Calories ?','500')||0,p=+prompt('Protéines (g) ?','30')||0,c=+prompt('Glucides (g) ?','50')||0,f=+prompt('Lipides (g) ?','15')||0;s.meals.push({name:n,kcal:k,p,c,f});s.eaten+=k;s.protein+=p;s.carbs+=c;s.fat+=f;save();render()}
function weight(){let w=+prompt('Poids actuel (kg) ?',s.weight);if(!w)return;s.weight=w;s.weights.push({date:new Date().toISOString(),weight:w});save();render();toast('Poids enregistré')}
function listen(){let SR=window.SpeechRecognition||window.webkitSpeechRecognition;if(!SR){toast('La dictée vocale n’est pas disponible ici.');return}if(rec){rec.stop();return}rec=new SR();rec.lang='fr-FR';rec.interimResults=false;rec.onresult=e=>{let t=e.results[0][0].transcript;toast('J’ai entendu : '+t);voice(t)};rec.onerror=e=>toast('Micro : '+e.error);rec.onend=()=>{rec=null;document.querySelector('#mic').textContent='🎙️'};document.querySelector('#mic').textContent='⏹️';toast('Je t’écoute…');rec.start()}
function voice(t){let m=t.match(/(?:poids|pèse|pesée).*?(\d+[,.]?\d*)\s*kg/i);if(m){s.weight=+m[1].replace(',','.');s.weights.push({date:new Date().toISOString(),weight:s.weight});save();render();toast('Poids enregistré');return}let k=t.match(/(\d+)\s*(?:kcal|calories)/i);if(/mangé|mange|repas|déjeun|dîné/i.test(t)){let kcal=k?+k[1]:0;s.meals.push({name:t,kcal,p:0,c:0,f:0});s.eaten+=kcal;save();render();toast('Repas ajouté');return}toast('Commande reçue. L’analyse IA arrive dans la prochaine version.')}
render();